fix(react-components): fixes issues with multiple rec widgets on one …
findify/findify-js pull request #632
Opened 2021-01-29 16:43 UTC by cMikolai

…page, ADA for the arrows and ar

affects: @findify/react-components

<!--

# 🎉 Thanks for taking the time to contribute to Findify! 🎉

It is highly appreciated that you take the time to help improve Findify.
We appreciate it if you would take the time to document your Pull Request.

Before submitting a new PR please read the [CONTRIBUTING.md](./CONTRIBUTING.md).

2021-02-05 15:58 UTC, Bitaru requested changes

2021-02-05 16:26 UTC, cMikolai commented on packages/react-components/src/layouts/Recommendation/Slider/view.tsx
> +      <svg width="11" height="19" className="findify-components--icon" xmlns="http://www.w3.org/2000/svg"><path d="M3.064 9.507L11 1.539 9.468 0 0 9.507 9.454 19l1.532-1.539z" fill="currentColor"></p
This point is adjusted :)

2021-02-05 16:30 UTC, cMikolai commented on packages/react-components/src/layouts/Recommendation/Slider/view.tsx
> +    <button aria-label="next" className={`findify-swiper-button-next ${config.get('slot')}-next`}>
@Bitaru As far as I understand, ${config.get('slot')}-next is providing the fix needed in order to have custom classNames needed in index.ts, so multiple rec widgets can be included on a single page and work correctly when the arrows are outside of the container etc (?)

```
navigation: {
        nextEl: `.${config.get('slot')}-next`,
        prevEl: `.${config.get('slot')}-prev`,
      },
```

2021-02-24 06:27 UTC, Bitaru approved these changes

2021-02-24 06:29 UTC, merged