feat/[DEV-1823]: Ability to enable/disable suggestions mobile autocomplete
findify/findify-js pull request #662
Opened 2021-04-06 10:13 UTC by andrej-naumovski

This PR adds a new flag to Autocomplete config which tells whether suggestions for mobile autocomplete are enabled or disabled.

2021-04-06 11:18 UTC, Bitaru requested changes

2021-04-06 11:18 UTC, Bitaru commented on packages/config/src/Autocomplete.ts
> +  enableSuggestionsOnMobileAutocomplete: boolean,
This option is already in config https://github.com/findify/findify-js/blob/6.17.0/packages/config/src/Autocomplete.ts#L20

2021-04-06 11:18 UTC, Bitaru commented on packages/react-components/src/layouts/Autocomplete/Dropdown/index.tsx
> +            <Suggestions
Better to use display-if

2021-04-14 13:41 UTC, andrej-naumovski commented
Closing due to issues with branches, will open a new clean PR.

2021-04-14 13:41 UTC, closed without merging